import type { Track } from "./types";

export const GRAMMAR_TRACK: Track = {
  id: "grammar",
  name: "Grammar",
  tagline: "The backbone — structures B1 → C2.",
  icon: "Blocks",
  lessons: [
    {
      id: "g1",
      level: "B1",
      order: 1,
      title: "Present Perfect vs Past Simple",
      concept: "tenses",
      blurb: "When the time is finished vs. connected to now.",
      teach: {
        intro:
          "Use the past simple for finished actions at a specific past time. Use the present perfect for past actions with a present result or an unfinished time period.",
        points: [
          "Past simple + a finished time marker: yesterday, in 2019, last week, ago.",
          "Present perfect + already / yet / just / ever / never / for / since.",
          "If you say exactly when, use the past simple — not the present perfect.",
        ],
        examples: [
          { text: "I visited Rome in 2019.", note: "finished time → past simple" },
          {
            text: "I have visited Rome three times.",
            note: "experience, time unfinished → present perfect",
          },
          { text: "She has just finished the report.", note: "'just' → present perfect" },
        ],
      },
      questions: [
        {
          id: "g1q1",
          type: "mcq",
          concept: "tenses",
          prompt: "I ___ my keys this morning, but I found them later.",
          choices: ["have lost", "lost", "have losed", "am losing"],
          answer: "lost",
          explanation:
            "'this morning' (now finished) + a specific resolved event → past simple.",
          flashFront: "Finished past time marker (e.g. 'this morning, yesterday') → which tense?",
          flashBack: "Past simple. E.g. 'I lost my keys this morning.'",
        },
        {
          id: "g1q2",
          type: "mcq",
          concept: "tenses",
          prompt: "We ___ each other since university.",
          choices: ["know", "knew", "have known", "are knowing"],
          answer: "have known",
          explanation: "'since' marks a period running up to now → present perfect.",
          flashFront: "'since 2010' / 'for ten years' → which tense?",
          flashBack: "Present perfect: 'We have known each other since university.'",
        },
        {
          id: "g1q3",
          type: "cloze",
          concept: "tenses",
          prompt: "Type the present perfect of 'finish': She ___ the project. (just)",
          answer: "has just finished",
          accept: ["has finished"],
          explanation: "'just' signals a recent action with present relevance → present perfect.",
          flashFront: "Present perfect of 'finish' (3rd person) with 'just'",
          flashBack: "has just finished",
        },
        {
          id: "g1q4",
          type: "mcq",
          concept: "tenses",
          prompt: "___ you ever ___ sushi?",
          choices: ["Did / eat", "Have / eaten", "Have / ate", "Do / ate"],
          answer: "Have / eaten",
          explanation: "'ever' (life experience, unfinished time) → present perfect.",
          flashFront: "Asking about life experience with 'ever' → which tense?",
          flashBack: "Present perfect: 'Have you ever eaten…?'",
        },
        {
          id: "g1q5",
          type: "type",
          concept: "tenses",
          prompt:
            "Correct the verb: 'I have seen that film last night.' → 'I ___ that film last night.'",
          answer: "saw",
          explanation: "'last night' is a finished time → past simple, not present perfect.",
          flashFront: "'…last night' forces which past tense?",
          flashBack: "Past simple: 'I saw it last night.' (not 'have seen … last night')",
        },
        {
          id: "g1q6",
          type: "mcq",
          concept: "tenses",
          prompt: "He ___ his homework yet.",
          choices: ["hasn't done", "didn't do", "doesn't do", "hasn't did"],
          answer: "hasn't done",
          explanation: "'yet' → present perfect (negative): hasn't done.",
          flashFront: "'…yet' in a negative → which tense?",
          flashBack: "Present perfect: 'He hasn't done it yet.'",
        },
      ],
    },
    {
      id: "g2",
      level: "B1",
      order: 2,
      title: "Conditionals (0, 1 & 2)",
      concept: "conditionals",
      blurb: "Facts, real future possibilities, and unreal situations.",
      teach: {
        intro:
          "Zero conditional = general truths (if + present, present). First = real future possibility (if + present, will). Second = unreal/hypothetical present (if + past, would).",
        points: [
          "Zero: If you heat ice, it melts.",
          "First: If it rains, I will stay home.",
          "Second: If I had more time, I would travel.",
          "Never use 'will' or 'would' in the 'if' clause.",
        ],
        examples: [
          { text: "If you press this, the light turns on.", note: "zero — a fact" },
          { text: "If I get the job, I'll move to Berlin.", note: "first — real possibility" },
          { text: "If I were you, I'd apologise.", note: "second — hypothetical ('were')" },
        ],
      },
      questions: [
        {
          id: "g2q1",
          type: "mcq",
          concept: "conditionals",
          prompt: "If I ___ rich, I would buy an island.",
          choices: ["am", "was", "were", "will be"],
          answer: "were",
          explanation: "Second conditional (unreal). Standard form uses 'were' for all persons.",
          flashFront: "Second conditional 'if I ___ you' — correct verb?",
          flashBack: "'were' — If I were you… (hypothetical, all persons).",
        },
        {
          id: "g2q2",
          type: "mcq",
          concept: "conditionals",
          prompt: "If it ___ tomorrow, we'll cancel the picnic.",
          choices: ["rains", "will rain", "would rain", "rained"],
          answer: "rains",
          explanation: "First conditional: present simple in the 'if' clause, 'will' in the main clause.",
          flashFront: "First conditional 'if' clause uses which tense?",
          flashBack: "Present simple. 'If it rains, we will cancel.'",
        },
        {
          id: "g2q3",
          type: "cloze",
          concept: "conditionals",
          prompt: "Zero conditional: If you ___ (mix) blue and yellow, you get green.",
          answer: "mix",
          explanation: "Zero conditional uses present simple in both clauses for general truths.",
          flashFront: "Zero conditional verb form (general truth)?",
          flashBack: "Present simple in both clauses: 'If you mix…, you get…'",
        },
        {
          id: "g2q4",
          type: "type",
          concept: "conditionals",
          prompt: "Complete with 'would': If I knew her number, I ___ call her.",
          answer: "would",
          explanation: "Second conditional main clause: would + base verb.",
          flashFront: "Second conditional main clause modal?",
          flashBack: "would + base verb: 'I would call her.'",
        },
        {
          id: "g2q5",
          type: "mcq",
          concept: "conditionals",
          prompt: "Which sentence is correct?",
          choices: [
            "If I will see him, I'll tell him.",
            "If I see him, I'll tell him.",
            "If I would see him, I tell him.",
            "If I saw him, I will tell him.",
          ],
          answer: "If I see him, I'll tell him.",
          explanation: "First conditional: no 'will' in the 'if' clause.",
          flashFront: "Can you use 'will' in the 'if' clause?",
          flashBack: "No. 'If I see him, I'll tell him.' (not 'If I will see')",
        },
        {
          id: "g2q6",
          type: "mcq",
          concept: "conditionals",
          prompt: "If she ___ harder, she would pass the exam.",
          choices: ["studies", "studied", "study", "will study"],
          answer: "studied",
          explanation: "Second conditional: past simple in the 'if' clause for an unreal present.",
          flashFront: "Second conditional 'if' clause tense?",
          flashBack: "Past simple: 'If she studied harder…' (unreal present)",
        },
      ],
    },
    {
      id: "g3",
      level: "B1",
      order: 3,
      title: "Articles: a / an / the / —",
      concept: "articles",
      blurb: "Choosing the right article (or none at all).",
      teach: {
        intro:
          "Use 'a/an' for a non-specific singular countable noun (first mention). Use 'the' when it's specific or already known. Use no article for general plural/uncountable nouns.",
        points: [
          "First mention → a/an; second mention → the.",
          "'the' for unique things: the sun, the internet.",
          "No article for general ideas: 'I like music', 'Cats are independent'.",
          "'an' before a vowel sound: an hour, a university.",
        ],
        examples: [
          { text: "I saw a dog. The dog was huge.", note: "a (new) → the (known)" },
          { text: "She plays the piano.", note: "instruments take 'the'" },
          { text: "Water is essential.", note: "general uncountable → no article" },
        ],
      },
      questions: [
        {
          id: "g3q1",
          type: "mcq",
          concept: "articles",
          prompt: "I need ___ umbrella; it's raining.",
          choices: ["a", "an", "the", "—"],
          answer: "an",
          explanation: "'umbrella' starts with a vowel sound → 'an'.",
          flashFront: "a or an before 'umbrella'?",
          flashBack: "an umbrella (vowel sound).",
        },
        {
          id: "g3q2",
          type: "mcq",
          concept: "articles",
          prompt: "She works at ___ university in Boston.",
          choices: ["a", "an", "the", "—"],
          answer: "a",
          explanation: "'university' starts with a /j/ (consonant) sound → 'a'.",
          flashFront: "a or an before 'university'?",
          flashBack: "a university (/j/ consonant sound).",
        },
        {
          id: "g3q3",
          type: "cloze",
          concept: "articles",
          prompt: "Type the article (or 'no'): ___ honesty is important. ",
          answer: "no",
          accept: ["no article", "none", "-", "—"],
          explanation: "General uncountable noun → no article.",
          flashFront: "Article before a general uncountable noun ('honesty')?",
          flashBack: "No article: 'Honesty is important.'",
        },
        {
          id: "g3q4",
          type: "mcq",
          concept: "articles",
          prompt: "We watched a film. ___ film was excellent.",
          choices: ["A", "An", "The", "—"],
          answer: "The",
          explanation: "Second mention of a known thing → 'the'.",
          flashFront: "Article on second mention of a known noun?",
          flashBack: "the — 'The film was excellent.'",
        },
        {
          id: "g3q5",
          type: "mcq",
          concept: "articles",
          prompt: "Can you play ___ guitar?",
          choices: ["a", "an", "the", "—"],
          answer: "the",
          explanation: "Musical instruments usually take 'the'.",
          flashFront: "Article before a musical instrument?",
          flashBack: "the — 'play the guitar/piano'.",
        },
        {
          id: "g3q6",
          type: "type",
          concept: "articles",
          prompt: "Fill the blank: ___ Earth orbits the Sun.",
          answer: "the",
          explanation: "Unique objects take 'the': the Earth, the Sun.",
          flashFront: "Article before unique objects (Earth, Sun)?",
          flashBack: "the — 'the Earth', 'the Sun'.",
        },
      ],
    },
    {
      id: "g4",
      level: "B2",
      order: 4,
      title: "Gerunds vs Infinitives",
      concept: "verb-patterns",
      blurb: "-ing or 'to' after another verb?",
      teach: {
        intro:
          "Some verbs are followed by a gerund (-ing), others by an infinitive (to + verb). A few change meaning depending on which you choose.",
        points: [
          "Gerund after: enjoy, avoid, finish, suggest, mind, keep, consider.",
          "Infinitive after: want, decide, hope, agree, plan, offer, promise.",
          "After prepositions, always use the gerund: 'good at singing'.",
          "'stop to do' (purpose) vs 'stop doing' (cease) change meaning.",
        ],
        examples: [
          { text: "I enjoy reading.", note: "enjoy + gerund" },
          { text: "She decided to leave.", note: "decide + infinitive" },
          { text: "He stopped smoking.", note: "ceased the activity" },
        ],
      },
      questions: [
        {
          id: "g4q1",
          type: "mcq",
          concept: "verb-patterns",
          prompt: "I really enjoy ___ to live music.",
          choices: ["listen", "to listen", "listening", "listened"],
          answer: "listening",
          explanation: "'enjoy' is always followed by a gerund (-ing).",
          flashFront: "enjoy + ?",
          flashBack: "gerund (-ing): 'enjoy listening'.",
        },
        {
          id: "g4q2",
          type: "mcq",
          concept: "verb-patterns",
          prompt: "They decided ___ the meeting.",
          choices: ["postponing", "to postpone", "postpone", "postponed"],
          answer: "to postpone",
          explanation: "'decide' takes the infinitive (to + verb).",
          flashFront: "decide + ?",
          flashBack: "infinitive (to + verb): 'decide to postpone'.",
        },
        {
          id: "g4q3",
          type: "cloze",
          concept: "verb-patterns",
          prompt: "After a preposition: She's good at ___ (solve) problems.",
          answer: "solving",
          explanation: "After a preposition ('at'), use the gerund.",
          flashFront: "Verb form after a preposition?",
          flashBack: "gerund: 'good at solving'.",
        },
        {
          id: "g4q4",
          type: "mcq",
          concept: "verb-patterns",
          prompt: "We should avoid ___ assumptions.",
          choices: ["to make", "making", "make", "made"],
          answer: "making",
          explanation: "'avoid' + gerund.",
          flashFront: "avoid + ?",
          flashBack: "gerund: 'avoid making'.",
        },
        {
          id: "g4q5",
          type: "type",
          concept: "verb-patterns",
          prompt: "Use the correct form of 'go': I want ___ home. (to + verb)",
          answer: "to go",
          explanation: "'want' takes the infinitive.",
          flashFront: "want + ?",
          flashBack: "infinitive: 'want to go'.",
        },
        {
          id: "g4q6",
          type: "mcq",
          concept: "verb-patterns",
          prompt: "On the drive, we stopped ___ a coffee. (purpose)",
          choices: ["drinking", "to drink", "drink", "drank"],
          answer: "to drink",
          explanation: "'stop to do' = stop in order to do something (purpose).",
          flashFront: "'stop to do' vs 'stop doing'?",
          flashBack: "'stop to do' = purpose; 'stop doing' = cease the activity.",
        },
      ],
    },
    {
      id: "g5",
      level: "B2",
      order: 5,
      title: "Relative Clauses",
      concept: "relative-clauses",
      blurb: "who, which, that, where — and when to drop them.",
      teach: {
        intro:
          "Relative clauses add information about a noun. Use 'who' for people, 'which' for things, 'that' for either (defining only), 'where' for places. Defining clauses take no commas; non-defining clauses use commas and cannot use 'that'.",
        points: [
          "Defining (essential, no commas): 'The man who called is my boss.'",
          "Non-defining (extra info, commas): 'My boss, who is 40, called.'",
          "You can omit the relative pronoun when it's the object: 'the book (that) I read'.",
          "Don't use 'that' in a non-defining clause.",
        ],
        examples: [
          { text: "The phone that I bought broke.", note: "defining, object → 'that' optional" },
          { text: "Paris, which I love, is busy.", note: "non-defining → commas, 'which'" },
          { text: "That's the café where we met.", note: "place → 'where'" },
        ],
      },
      questions: [
        {
          id: "g5q1",
          type: "mcq",
          concept: "relative-clauses",
          prompt: "The scientist ___ discovered this won a prize.",
          choices: ["which", "who", "where", "whom"],
          answer: "who",
          explanation: "Subject + person → 'who'.",
          flashFront: "Relative pronoun for a person (subject)?",
          flashBack: "who — 'the scientist who discovered…'.",
        },
        {
          id: "g5q2",
          type: "mcq",
          concept: "relative-clauses",
          prompt: "This is the laptop ___ I told you about.",
          choices: ["who", "where", "which", "whose"],
          answer: "which",
          explanation: "A thing → 'which' (or 'that'). 'who' is for people.",
          flashFront: "Relative pronoun for a thing?",
          flashBack: "which / that — 'the laptop which/that…'.",
        },
        {
          id: "g5q3",
          type: "mcq",
          concept: "relative-clauses",
          prompt: "Which is a correct non-defining clause?",
          choices: [
            "My brother that lives in Spain called.",
            "My brother, who lives in Spain, called.",
            "My brother, that lives in Spain, called.",
            "My brother which lives in Spain called.",
          ],
          answer: "My brother, who lives in Spain, called.",
          explanation: "Non-defining clauses use commas and 'who/which' — never 'that'.",
          flashFront: "Can you use 'that' in a non-defining clause?",
          flashBack: "No — use who/which with commas.",
        },
        {
          id: "g5q4",
          type: "cloze",
          concept: "relative-clauses",
          prompt: "Place: That's the town ___ I grew up.",
          answer: "where",
          explanation: "Reference to a place → 'where'.",
          flashFront: "Relative word for a place?",
          flashBack: "where — 'the town where I grew up'.",
        },
        {
          id: "g5q5",
          type: "mcq",
          concept: "relative-clauses",
          prompt: "In which sentence can the relative pronoun be omitted?",
          choices: [
            "The woman who lives next door is a vet.",
            "The book that I read was great.",
            "The road that leads north is closed.",
            "The student who won is here.",
          ],
          answer: "The book that I read was great.",
          explanation: "You can drop the pronoun only when it's the object of the clause.",
          flashFront: "When can you omit the relative pronoun?",
          flashBack: "When it's the object: 'the book (that) I read'.",
        },
        {
          id: "g5q6",
          type: "type",
          concept: "relative-clauses",
          prompt: "Possession: The author ___ book won the prize is here. (one word)",
          answer: "whose",
          explanation: "Possessive relative pronoun → 'whose'.",
          flashFront: "Possessive relative pronoun?",
          flashBack: "whose — 'the author whose book…'.",
        },
      ],
    },
    {
      id: "g6",
      level: "C1",
      order: 6,
      title: "Inversion for Emphasis",
      concept: "inversion",
      blurb: "Negative adverbials that flip subject and auxiliary.",
      teach: {
        intro:
          "When a negative or limiting adverbial starts a sentence for emphasis, English inverts the subject and auxiliary, just like a question. This is a hallmark of formal, advanced style.",
        points: [
          "Triggers: Never, Rarely, Seldom, Hardly, No sooner … than, Not only … but also, Little, Only then.",
          "Form: adverbial + auxiliary + subject + main verb.",
          "If there's no auxiliary, add 'do/does/did': 'Never did I imagine…'.",
          "'No sooner had I … than …' and 'Hardly had I … when …' are fixed patterns.",
        ],
        examples: [
          { text: "Never have I seen such a mess.", note: "Never + have + I…" },
          { text: "No sooner had we left than it rained.", note: "fixed 'No sooner … than'" },
          { text: "Not only is she clever, but she is also kind.", note: "Not only + is + she" },
        ],
      },
      questions: [
        {
          id: "g6q1",
          type: "mcq",
          concept: "inversion",
          prompt: "Never ___ such a beautiful sunset.",
          choices: ["I have seen", "have I seen", "I saw", "did I saw"],
          answer: "have I seen",
          explanation: "After a fronted 'Never', invert auxiliary and subject: have I seen.",
          flashFront: "'Never ___ such…' — word order?",
          flashBack: "Invert: 'Never have I seen such…'",
        },
        {
          id: "g6q2",
          type: "mcq",
          concept: "inversion",
          prompt: "___ had I sat down than the phone rang.",
          choices: ["No sooner", "Hardly", "Rarely", "Seldom"],
          answer: "No sooner",
          explanation: "'No sooner … than' is the fixed pair; 'Hardly … when'.",
          flashFront: "'___ had I sat down than…' — which adverbial?",
          flashBack: "No sooner … than (Hardly … when).",
        },
        {
          id: "g6q3",
          type: "type",
          concept: "inversion",
          prompt: "Add the auxiliary: 'Little ___ he know the truth.' (one word)",
          answer: "did",
          explanation: "With no existing auxiliary, add 'did': 'Little did he know'.",
          flashFront: "'Little ___ he know' — auxiliary?",
          flashBack: "did — 'Little did he know'.",
        },
        {
          id: "g6q4",
          type: "mcq",
          concept: "inversion",
          prompt: "Which sentence is correct?",
          choices: [
            "Only then I understood the problem.",
            "Only then did I understand the problem.",
            "Only then understood I the problem.",
            "Only then I did understand the problem.",
          ],
          answer: "Only then did I understand the problem.",
          explanation: "'Only then' triggers inversion with 'did' + subject + base verb.",
          flashFront: "'Only then ___ I understand' — form?",
          flashBack: "Only then did I understand…",
        },
        {
          id: "g6q5",
          type: "cloze",
          concept: "inversion",
          prompt: "Rewrite the start: Not only ___ (be) he late, but he also forgot the tickets.",
          answer: "was",
          explanation: "'Not only' fronted → invert: 'Not only was he late…'.",
          flashFront: "'Not only ___ he late' — verb position?",
          flashBack: "Invert: 'Not only was he late…'",
        },
        {
          id: "g6q6",
          type: "mcq",
          concept: "inversion",
          prompt: "Rarely ___ a politician admit a mistake so openly.",
          choices: ["does", "do", "is", "has"],
          answer: "does",
          explanation: "'Rarely' + inversion; singular subject → 'does' + base verb.",
          flashFront: "'Rarely ___ a politician admit…' — auxiliary?",
          flashBack: "does — 'Rarely does a politician admit…'",
        },
      ],
    },
    {
      id: "g7",
      level: "C2",
      order: 7,
      title: "Cleft & Nominalisation",
      concept: "cleft-sentences",
      blurb: "Reshaping clauses for focus and an academic register.",
      teach: {
        intro:
          "Cleft sentences split one idea into two clauses to focus a specific element ('It was X that…', 'What I need is…'). Nominalisation turns verbs/adjectives into nouns for a denser, more formal register.",
        points: [
          "It-cleft: 'It was the noise that woke me.' (focus = the noise)",
          "Wh-cleft: 'What surprised me was his calm.' (focus comes after 'was')",
          "Nominalisation: 'They decided quickly' → 'Their quick decision…'.",
          "Nominalised style is typical of academic and formal writing.",
        ],
        examples: [
          { text: "It was patience that solved it.", note: "it-cleft focuses 'patience'" },
          { text: "What he wants is recognition.", note: "wh-cleft focuses 'recognition'" },
          { text: "The implementation of the policy failed.", note: "nominalised 'implement'" },
        ],
      },
      questions: [
        {
          id: "g7q1",
          type: "mcq",
          concept: "cleft-sentences",
          prompt: "Focus 'her support': ___ that helped me most.",
          choices: ["It was her support", "What her support", "There was her support", "Her support it was"],
          answer: "It was her support",
          explanation: "It-cleft: 'It was [focus] that…'.",
          flashFront: "It-cleft pattern to focus a noun?",
          flashBack: "'It was [X] that…' — 'It was her support that helped.'",
        },
        {
          id: "g7q2",
          type: "mcq",
          concept: "cleft-sentences",
          prompt: "Complete the wh-cleft: ___ is a clear plan.",
          choices: [
            "What we need",
            "That we need",
            "It we need",
            "Which we need",
          ],
          answer: "What we need",
          explanation: "Wh-cleft starts with 'What …' and puts the focus after 'is'.",
          flashFront: "Wh-cleft opener?",
          flashBack: "'What … is …' — 'What we need is a clear plan.'",
        },
        {
          id: "g7q3",
          type: "type",
          concept: "cleft-sentences",
          prompt: "Nominalise 'decide': Use the noun — 'Their ___ to expand was bold.'",
          answer: "decision",
          explanation: "Verb 'decide' → noun 'decision' for a nominalised, formal style.",
          flashFront: "Noun form of 'decide'?",
          flashBack: "decision — 'their decision to expand'.",
        },
        {
          id: "g7q4",
          type: "mcq",
          concept: "cleft-sentences",
          prompt: "Which is a correctly nominalised, formal version of 'because prices rose'?",
          choices: [
            "due to the rise in prices",
            "because prices were rising up",
            "as prices they rose",
            "for the reason prices rose",
          ],
          answer: "due to the rise in prices",
          explanation: "Nominalisation turns the clause into a noun phrase: 'the rise in prices'.",
          flashFront: "Nominalise 'because prices rose'?",
          flashBack: "'due to the rise in prices'.",
        },
        {
          id: "g7q5",
          type: "cloze",
          concept: "cleft-sentences",
          prompt: "It-cleft for time: 'It ___ in 1990 that the company was founded.' (one word)",
          answer: "was",
          explanation: "It-cleft uses 'It was … that …' even for time references.",
          flashFront: "It-cleft verb: 'It ___ in 1990 that…'?",
          flashBack: "was — 'It was in 1990 that…'.",
        },
        {
          id: "g7q6",
          type: "mcq",
          concept: "cleft-sentences",
          prompt: "Reverse wh-cleft: 'A holiday is ___ she really needs.'",
          choices: ["what", "that", "which", "it"],
          answer: "what",
          explanation: "Reverse wh-cleft puts focus first: '[X] is what …'.",
          flashFront: "'A holiday is ___ she needs' — relative word?",
          flashBack: "what — '… is what she needs'.",
        },
      ],
    },
  ],
};
