import type { Track } from "./types";

export const READING_TRACK: Track = {
  id: "reading",
  name: "Reading",
  tagline: "Read short texts, then prove you understood them.",
  icon: "BookOpen",
  lessons: [
    {
      id: "r1",
      level: "B1",
      order: 1,
      title: "Skimming for the Main Idea",
      concept: "main-idea",
      blurb: "A short text + comprehension questions.",
      passage:
        "Maya had always taken the same route to work: a crowded bus that turned a fifteen-minute trip into forty. One morning, the bus broke down, so she decided to walk. To her surprise, the walk took only twenty-five minutes, and she arrived feeling calm rather than stressed. From that day on, she walked whenever the weather allowed. She slept better, spent less money, and noticed small things in her neighbourhood she had never seen from the bus window.",
      teach: {
        intro:
          "Skim first to grasp the main idea, then read details. The main idea is the writer's central point — not just the first thing mentioned.",
        points: [
          "Ask: what is the whole text mostly about?",
          "Distinguish the main idea from supporting details.",
          "Watch for the result/change a story builds toward.",
        ],
        examples: [
          { text: "A change in habit leads to unexpected benefits.", note: "main idea of the text" },
        ],
      },
      questions: [
        {
          id: "r1q1",
          type: "mcq",
          concept: "main-idea",
          prompt: "What is the main idea of the passage?",
          choices: [
            "Buses are always unreliable.",
            "Changing a habit brought Maya unexpected benefits.",
            "Maya was late to work one day.",
            "Walking is dangerous in bad weather.",
          ],
          answer: "Changing a habit brought Maya unexpected benefits.",
          explanation: "The whole text builds toward the benefits of her new walking habit.",
          flashFront: "Main idea of the Maya passage?",
          flashBack: "A changed habit (walking) brought unexpected benefits.",
        },
        {
          id: "r1q2",
          type: "mcq",
          concept: "main-idea",
          prompt: "Why did Maya walk the first time?",
          choices: [
            "She wanted exercise.",
            "The bus broke down.",
            "She missed the bus.",
            "It was a sunny day.",
          ],
          answer: "The bus broke down.",
          explanation: "The text says the bus broke down, so she decided to walk.",
          flashFront: "Why did Maya first walk to work?",
          flashBack: "The bus broke down.",
        },
        {
          id: "r1q3",
          type: "mcq",
          concept: "main-idea",
          prompt: "Which is a detail, NOT the main idea?",
          choices: [
            "She slept better after walking.",
            "Changing habits can have benefits.",
            "Small changes affected her life.",
            "The walk improved her mornings.",
          ],
          answer: "She slept better after walking.",
          explanation: "Sleeping better is one supporting detail, not the overall point.",
          flashFront: "Main idea vs detail — which is a detail?",
          flashBack: "A specific benefit (e.g. 'slept better') is a detail.",
        },
        {
          id: "r1q4",
          type: "type",
          concept: "main-idea",
          prompt: "How long did the walk take? (number + word, e.g. 'ten minutes')",
          answer: "twenty-five minutes",
          accept: ["25 minutes", "twentyfive minutes"],
          explanation: "The text states the walk took only twenty-five minutes.",
          flashFront: "How long was Maya's walk?",
          flashBack: "Twenty-five minutes.",
        },
        {
          id: "r1q5",
          type: "mcq",
          concept: "main-idea",
          prompt: "How did Maya feel after walking, compared to the bus?",
          choices: ["More stressed", "Calm", "Bored", "Tired"],
          answer: "Calm",
          explanation: "She 'arrived feeling calm rather than stressed'.",
          flashFront: "How did walking make Maya feel?",
          flashBack: "Calm (rather than stressed).",
        },
        {
          id: "r1q6",
          type: "cloze",
          concept: "vocabulary-in-context",
          prompt: "In context, 'to her surprise' means the result was ___ (un-).",
          answer: "unexpected",
          accept: ["surprising"],
          explanation: "'to her surprise' signals something unexpected.",
          flashFront: "'to her surprise' = ?",
          flashBack: "unexpected / surprising",
        },
      ],
    },
    {
      id: "r2",
      level: "B2",
      order: 2,
      title: "Inference & Tone",
      concept: "inference",
      blurb: "Read between the lines of an opinion piece.",
      passage:
        "It is often claimed that remote work spells the end of the traditional office. Yet the evidence is more nuanced. While many employees report higher productivity at home, others struggle with isolation and blurred boundaries between work and rest. Companies, too, are divided: some celebrate lower costs, while others worry that creativity suffers without spontaneous, face-to-face conversation. The likely outcome is not the death of the office but its reinvention as a place for collaboration rather than routine tasks.",
      teach: {
        intro:
          "Inference means drawing a reasonable conclusion the writer implies but doesn't state directly. Tone is the writer's attitude (e.g. balanced, critical, enthusiastic).",
        points: [
          "Look for hedging words: 'often claimed', 'likely', 'more nuanced'.",
          "A balanced tone presents multiple sides before a measured conclusion.",
          "Infer the writer's position from the conclusion, not a single line.",
        ],
        examples: [
          { text: "The writer is balanced, not one-sided.", note: "tone inference" },
        ],
      },
      questions: [
        {
          id: "r2q1",
          type: "mcq",
          concept: "inference",
          prompt: "What does the writer most likely believe about the office?",
          choices: [
            "It will disappear completely.",
            "It will be reinvented, not abolished.",
            "It should never change.",
            "Remote work is always better.",
          ],
          answer: "It will be reinvented, not abolished.",
          explanation: "The conclusion: 'not the death of the office but its reinvention'.",
          flashFront: "Writer's view on the office's future?",
          flashBack: "Reinvented (for collaboration), not abolished.",
        },
        {
          id: "r2q2",
          type: "mcq",
          concept: "inference",
          prompt: "How would you best describe the tone?",
          choices: ["Balanced", "Angry", "Sarcastic", "Fearful"],
          answer: "Balanced",
          explanation: "The text weighs pros and cons before a measured conclusion.",
          flashFront: "Tone of the remote-work passage?",
          flashBack: "Balanced / measured.",
        },
        {
          id: "r2q3",
          type: "mcq",
          concept: "inference",
          prompt: "'The evidence is more nuanced' implies the writer thinks the claim is ___.",
          choices: ["completely true", "too simple", "irrelevant", "dishonest"],
          answer: "too simple",
          explanation: "'more nuanced' signals the simple claim misses complexity.",
          flashFront: "'more nuanced' implies the claim is…?",
          flashBack: "Too simple / oversimplified.",
        },
        {
          id: "r2q4",
          type: "mcq",
          concept: "inference",
          prompt: "What downside of remote work is mentioned for employees?",
          choices: [
            "Lower pay",
            "Isolation and blurred boundaries",
            "Longer commutes",
            "Less technology",
          ],
          answer: "Isolation and blurred boundaries",
          explanation: "Some 'struggle with isolation and blurred boundaries'.",
          flashFront: "Employee downside of remote work in the text?",
          flashBack: "Isolation; blurred work/rest boundaries.",
        },
        {
          id: "r2q5",
          type: "cloze",
          concept: "vocabulary-in-context",
          prompt: "In context, 'spontaneous' conversations are ones that are ___ (not planned).",
          answer: "unplanned",
          accept: ["unexpected", "natural"],
          explanation: "'spontaneous' = happening naturally, without planning.",
          flashFront: "'spontaneous' = ?",
          flashBack: "unplanned / natural",
        },
        {
          id: "r2q6",
          type: "mcq",
          concept: "inference",
          prompt: "Why might companies worry about full remote work?",
          choices: [
            "Higher office costs",
            "Creativity may suffer without face-to-face contact",
            "Employees work too much",
            "Technology is too cheap",
          ],
          answer: "Creativity may suffer without face-to-face contact",
          explanation: "The text says some worry 'creativity suffers without … conversation'.",
          flashFront: "Company worry about remote work?",
          flashBack: "Creativity may suffer without face-to-face contact.",
        },
      ],
    },
  ],
};
