import type { Track } from "./types";

export const VOCABULARY_TRACK: Track = {
  id: "vocabulary",
  name: "Vocabulary",
  tagline: "Upgrade everyday words to precise, advanced ones.",
  icon: "BookA",
  lessons: [
    {
      id: "v1",
      level: "B1",
      order: 1,
      title: "Stronger Everyday Adjectives",
      concept: "adjectives",
      blurb: "Trade 'very + adjective' for one vivid word.",
      teach: {
        intro:
          "Advanced speakers replace 'very + adjective' with a single strong adjective. This sounds more natural and precise.",
        points: [
          "very tired → exhausted",
          "very hungry → starving",
          "very big → enormous / huge",
          "very small → tiny",
          "very interesting → fascinating",
        ],
        examples: [
          { text: "I'm exhausted after the trip.", note: "not 'very tired'" },
          { text: "The stadium was enormous.", note: "not 'very big'" },
          { text: "It was a fascinating talk.", note: "not 'very interesting'" },
        ],
      },
      questions: [
        {
          id: "v1q1",
          type: "mcq",
          concept: "adjectives",
          prompt: "Choose the strongest single word for 'very tired'.",
          choices: ["sleepy", "exhausted", "bored", "lazy"],
          answer: "exhausted",
          explanation: "'exhausted' = very tired in one word.",
          flashFront: "Single strong word for 'very tired'?",
          flashBack: "exhausted",
        },
        {
          id: "v1q2",
          type: "mcq",
          concept: "adjectives",
          prompt: "'very hungry' = ?",
          choices: ["starving", "thirsty", "eager", "greedy"],
          answer: "starving",
          explanation: "'starving' (informal) = very hungry.",
          flashFront: "Single word for 'very hungry'?",
          flashBack: "starving",
        },
        {
          id: "v1q3",
          type: "type",
          concept: "adjectives",
          prompt: "One word for 'very big' (starts with e): ___",
          answer: "enormous",
          accept: ["huge", "gigantic"],
          explanation: "enormous / huge / gigantic = very big.",
          flashFront: "Strong word for 'very big' (e-)?",
          flashBack: "enormous (also huge, gigantic).",
        },
        {
          id: "v1q4",
          type: "mcq",
          concept: "adjectives",
          prompt: "'very interesting' = ?",
          choices: ["boring", "fascinating", "confusing", "ordinary"],
          answer: "fascinating",
          explanation: "'fascinating' = very interesting.",
          flashFront: "Single word for 'very interesting'?",
          flashBack: "fascinating",
        },
        {
          id: "v1q5",
          type: "cloze",
          concept: "adjectives",
          prompt: "The mouse was ___ (very small): t___.",
          answer: "tiny",
          explanation: "'tiny' = very small.",
          flashFront: "Single word for 'very small'?",
          flashBack: "tiny",
        },
        {
          id: "v1q6",
          type: "mcq",
          concept: "adjectives",
          prompt: "'very surprised' = ?",
          choices: ["amazed", "annoyed", "amused", "ashamed"],
          answer: "amazed",
          explanation: "'amazed / astonished' = very surprised.",
          flashFront: "Single word for 'very surprised'?",
          flashBack: "amazed / astonished",
        },
      ],
    },
    {
      id: "v2",
      level: "B2",
      order: 2,
      title: "Collocations with 'make' & 'do'",
      concept: "collocations",
      blurb: "Which verb partners which noun?",
      teach: {
        intro:
          "'make' and 'do' are not interchangeable. Learn them as fixed collocations rather than translating word by word.",
        points: [
          "make: a decision, a mistake, progress, an effort, a difference, money.",
          "do: homework, the dishes, business, research, a favour, your best.",
          "Rough rule: 'make' = create/produce; 'do' = perform an activity.",
        ],
        examples: [
          { text: "She made a difficult decision.", note: "make a decision" },
          { text: "He did me a favour.", note: "do a favour" },
          { text: "We made good progress.", note: "make progress" },
        ],
      },
      questions: [
        {
          id: "v2q1",
          type: "mcq",
          concept: "collocations",
          prompt: "I need to ___ a decision by Friday.",
          choices: ["do", "make", "take", "have"],
          answer: "make",
          explanation: "'make a decision' is the fixed collocation.",
          flashFront: "make or do + 'a decision'?",
          flashBack: "make a decision",
        },
        {
          id: "v2q2",
          type: "mcq",
          concept: "collocations",
          prompt: "Could you ___ me a favour?",
          choices: ["make", "do", "give", "put"],
          answer: "do",
          explanation: "'do someone a favour'.",
          flashFront: "make or do + 'a favour'?",
          flashBack: "do a favour",
        },
        {
          id: "v2q3",
          type: "type",
          concept: "collocations",
          prompt: "We've ___ a lot of progress this term. (make/do, past)",
          answer: "made",
          explanation: "'make progress' → past 'made progress'.",
          flashFront: "make or do + 'progress'?",
          flashBack: "make progress (made progress).",
        },
        {
          id: "v2q4",
          type: "mcq",
          concept: "collocations",
          prompt: "He's away on a trip to ___ business.",
          choices: ["make", "do", "have", "take"],
          answer: "do",
          explanation: "'do business' (with someone).",
          flashFront: "make or do + 'business'?",
          flashBack: "do business",
        },
        {
          id: "v2q5",
          type: "mcq",
          concept: "collocations",
          prompt: "Don't worry if you ___ a mistake.",
          choices: ["do", "make", "take", "get"],
          answer: "make",
          explanation: "'make a mistake'.",
          flashFront: "make or do + 'a mistake'?",
          flashBack: "make a mistake",
        },
        {
          id: "v2q6",
          type: "cloze",
          concept: "collocations",
          prompt: "Just ___ your best — that's enough. (make/do)",
          answer: "do",
          explanation: "'do your best'.",
          flashFront: "make or do + 'your best'?",
          flashBack: "do your best",
        },
      ],
    },
    {
      id: "v3",
      level: "C1",
      order: 3,
      title: "Precise Verbs for 'say' & 'look'",
      concept: "precise-verbs",
      blurb: "Swap vague verbs for exact, advanced ones.",
      teach: {
        intro:
          "Advanced writing chooses the most precise verb. Instead of always using 'say' or 'look', pick a verb that carries the manner and intent.",
        points: [
          "say angrily → snap; say quietly → murmur/whisper; say firmly → insist/assert.",
          "look quickly → glance; look long/angrily → glare; look closely → examine/scrutinise.",
          "Precise verbs remove the need for an adverb.",
        ],
        examples: [
          { text: "'Stop it,' she snapped.", note: "snap = say sharply/angrily" },
          { text: "He glanced at his watch.", note: "glance = look quickly" },
          { text: "She scrutinised the contract.", note: "scrutinise = examine closely" },
        ],
      },
      questions: [
        {
          id: "v3q1",
          type: "mcq",
          concept: "precise-verbs",
          prompt: "To 'look quickly' is to ___.",
          choices: ["glare", "glance", "gaze", "stare"],
          answer: "glance",
          explanation: "'glance' = a quick look; 'glare/stare/gaze' are long looks.",
          flashFront: "Verb for 'look quickly'?",
          flashBack: "glance",
        },
        {
          id: "v3q2",
          type: "mcq",
          concept: "precise-verbs",
          prompt: "To 'look angrily for a long time' is to ___.",
          choices: ["glance", "peek", "glare", "wink"],
          answer: "glare",
          explanation: "'glare' = an angry, fixed look.",
          flashFront: "Verb for 'look angrily'?",
          flashBack: "glare",
        },
        {
          id: "v3q3",
          type: "mcq",
          concept: "precise-verbs",
          prompt: "'\"Be quiet,\" he ___' (said sharply and angrily).",
          choices: ["whispered", "snapped", "mumbled", "announced"],
          answer: "snapped",
          explanation: "'snap' = say something sharply/angrily.",
          flashFront: "Verb for 'say sharply/angrily'?",
          flashBack: "snap",
        },
        {
          id: "v3q4",
          type: "type",
          concept: "precise-verbs",
          prompt: "One verb for 'say very quietly' (w___):",
          answer: "whisper",
          accept: ["murmur"],
          explanation: "'whisper' / 'murmur' = say very quietly.",
          flashFront: "Verb for 'say very quietly'?",
          flashBack: "whisper / murmur",
        },
        {
          id: "v3q5",
          type: "mcq",
          concept: "precise-verbs",
          prompt: "To 'look closely and critically' is to ___.",
          choices: ["scrutinise", "glimpse", "glance", "spot"],
          answer: "scrutinise",
          explanation: "'scrutinise' = examine closely and critically.",
          flashFront: "Verb for 'examine closely/critically'?",
          flashBack: "scrutinise / examine",
        },
        {
          id: "v3q6",
          type: "cloze",
          concept: "precise-verbs",
          prompt: "Replace 'said again to confirm': 'I won't go,' she ___ed. (r-)",
          answer: "reiterate",
          accept: ["repeat", "reaffirm", "reiterated", "repeated"],
          explanation: "'reiterate' = say again to confirm/emphasise.",
          flashFront: "Verb for 'say again to confirm'?",
          flashBack: "reiterate / reaffirm",
        },
      ],
    },
  ],
};
